### PR TITLE
Added hasOwnProperty check

### PR DESCRIPTION
**Pull request by mayacoda**
jQuery adds .has() and .capitalize() methods to strings.

### CODE REVIEW

**Comment by duncanmcdowell** [comment]
This looks good to me

**Comment by SamMaier** [comment]
This needs a different solution. I believe the ```for (var a in differences[0])``` is just shorthand for ```for (var a = 0; a < differences.length; a++)```. I don't think throwing a ```hasOwnProperty``` check makes sense in that context.

**Comment by MichaelF2** [comment]
@SamMaier This is not true.  "For ... in" loops iterate over the properties of an object.  This can be misleading for arrays, but the code change is valid.

**Comment by SamMaier** [comment]
Looked into it more - you're right. I'm going to merge this one.

**Pull request merged**
