### PR TITLE
changed unequalVariable call from dot to array notation

### PR DESCRIPTION
**Pull request by mayacoda**
This should fix $parse issue that was being caused by using dot notation.

### CODE REVIEW

**Comment by duncanmcdowell** [comment]
Is this meant to address issue #34 ?

**Comment by mayacoda** [comment]
Yes, I actually had the same problem and didn't notice there was an issue open. It works for me in practice, but I'm now seeing that the tests fail. Silly me not to notice that..

**Comment by duncanmcdowell** [comment]
Fairly certain all the tests are failing :) 

I think we may have hooked up travis at one point but never followed through on having it build properly

**Comment by SamMaier** [comment]
Travis was never hooked up as far as I know. Tests have only ever been run locally. If I get a chance I will run these locally and see what happens. One request I'd have that if it fixes an issue, you push your PR with a simple unit test which fails the case which you are fixing - it would save me a bunch of time on the review if that was possible. Thanks!

**Pull request closed without merging**
